homeserver:
  address: http://192.168.10.16:8008
  domain: jauriarts.org
  verify_ssl: 1

spring:
  address: 192.168.10.16
  port: 8200
  ssl: False
  bot_username: appservice
  bot_password: pladur13lol
  client_name: "Appservice 0.1"

appservice:
  as_token: "wfghWEGh3wgWHEf3478sHFWE"
  hs_token: "ugw8243igya57aaABGFfgeyu"
  bot_username: appservice
  namespace: jauria
  max_body_size: 1
  address: http://localhost:8080
  hostname: 127.0.0.1
  port: 8080

  admin_list:
    - "@id_30072:springrts.com"
    - "@turboss:jauriarts.org"
    - "@TurBoss:matrix.org"
    - "@id_174613:springrts.com"

  admin_room: "!GBmLddDuJusAGHXEpB:matrix.org"

  bridge:

    test:
      room_id: "!ckgUuMKcgcfJHSTvDP:jauriarts.org"
      enabled: 1

    sy:
      room_id: "!QnNgrBOChCJVVqWWjY:matrix.org"
      enabled: 1

    springlobby:
      room_id: "!xIAWDQuQEDFzSllXML:springrts.com"
      enabled: 1

    s44:
      room_id: "!EoIGLmjIYqPSFLNWVn:matrix.org"
      enabled: 1

    chobby:
      room_id: "!xfGxczxAywmNfAdXIk:springrts.com"
      enabled: 1

    mapping:
      room_id: "!cnxlPotDhFgdBaswag:matrix.org"
      enabled: 1

    gamedev:
      room_id: "!DpMgMbnDzOvUIXvoTX:jauriarts.org"
      enabled: 1

# Python logging configuration.
#
# See section 16.7.2 of the Python documentation for more info:
# https://docs.python.org/3.6/library/logging.config.html#configuration-dictionary-schema
logging:
  version: 1
  formatters:
    precise:
      format: "[%(asctime)s] [%(levelname)s@%(name)s] %(message)s"
  handlers:
    file:
      class: logging.handlers.RotatingFileHandler
      formatter: precise
      filename: ./matrix-spring.log
      maxBytes: 10485760
      backupCount: 10
    console:
      class: logging.StreamHandler
      formatter: precise
  loggers:
    matrix-spring:
      level: DEBUG
    spring_as:
      level: DEBUG
    asyncspring:
      level: INFO
    aiohttp:
      level: DEBUG
  root:
    level: DEBUG
    handlers:
      - file
      - console
